apiVersion: v1
kind: Service
metadata:
  name: ufodb-service
  namespace: ufology
  labels:
    app: ufodb
spec:
  type: ClusterIP
  selector:
    app: ufodb
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432